Move reading records into with-block in capacity check
When running the tests with sqlite, the tests fail with:

    sqlalchemy.exc.ResourceClosedError: This Connection is closed

Moving reading the records from the cursor into the with-block of the
independent transaction fixes this.

Reading all the records at once shouldn't be a problem memory-wise,
because we save all the records anyways.

Change-Id: I5bb5fad072e514de5b8e531c9fef40ddbd724fac